apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
        generateName: dag-pipeline-
spec:
        entrypoint: dag-pipeline
        templates:
                - name: dag-pipeline
                  dag:
                      tasks:
                            - name: detection-template
                              template: detection-template


                - name: detection-template
                  script:
                                image: alpine
                                command: [sleep, "abc"]
                                source: |
                                    echo "Hello World !"
                                resources:
                                  requests:
                                          nvidia.com/gpu: "1"
                                          cpu: 4
                                          memory: 5Gi
                                  limits:
                                          nvidia.com/gpu: "1"
                                          cpu: 4
                                          memory: 5Gi
