apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-passing-
spec:
  entrypoint: artifact-example
  podGC:
    strategy: OnPodSuccess
  templates:
  - name: artifact-example
    steps:
    - - name: generate-artifact
        template: whalesay
    - - name: consume-artifact
        template: print-message
        arguments:
            artifacts:
            - name: message
              from: "{{steps.generate-artifact.outputs.artifacts.hello-argo}}"

  - name: whalesay
    container:
        image: docker/whalesay:latest
        command: [sh, -c]
        args: ["sleep 1; echo -n hello Argo > /tmp/hello_argo.txt"]
    outputs:
        artifacts:
        - name: hello-argo
          path: /tmp/hello_argo.txt

  - name: print-message
    inputs:
        artifacts:
        - name: message
          path: /tmp/message
    container:
        image: alpine:latest
        command: [sh, -c]
        args: ["cat /tmp/message"]
